version: "3"
services:
  app:
    image: vzlomed/vzlomed:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:alpine
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - .:/app
    command:
      - "redis-server"
      - "--loglevel ${REDIS_LOGLEVEL:-warning}"
      - "--save 120 1"
      - "--maxmemory ${REDIS_MAXMEM:-50mb}"
      - "--maxmemory-policy ${REDIS_POLICY:-noeviction}"
      - "--requirepass ${REDIS_PWD}"
  mongo:
    image: bitnami/mongodb:latest
    networks:
      - app_network
    restart: unless-stopped
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PWD}
      MONGODB_DATABASE: ${MONGO_DB_ACCESS}
      MONGODB_PORT_NUMBER: ${MONGO_PORT}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
networks:
  app_network:
volumes:
  redis_data:
  mongo:
